=== K-Rhen/sqltransfer/src/main/resources/sqltransfer.xsd
<?xml version="1.0"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	elementFormDefault="qualified"
	targetNamespace="http://www.topdesk.com" 
	xmlns="http://www.topdesk.com"
>
	<xs:element name="ldap">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="server" type="xs:string"/>
				<xs:element name="port" default="389">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="1" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="basedn" type="xs:string"/>
				<xs:element name="user" type="xs:string"/>
				<xs:element name="password" type="xs:string"/>
				<xs:element name="pagesize" minOccurs="0" default="0">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="0" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="secure" type="xs:boolean" minOccurs="0" default="false"/>
				<xs:element name="referral" minOccurs="0"  default="follow">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="ignore" />
							<xs:enumeration value="follow" />
							<xs:enumeration value="throw" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="jdbc">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="driver" type="xs:string"/>
				<xs:element name="url" type="xs:string"/>
				<xs:element name="user" type="xs:string"/>
				<xs:element name="password" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:group name="connectiongroup">
		<xs:choice>
			<xs:element ref="jdbc"/>
			<xs:element ref="ldap"/>
		</xs:choice>
	</xs:group>
	<xs:element name="ldaptransfer">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="contexts" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="context" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ldapquery" type="xs:string" minOccurs="0"/>
				<xs:element name="attributes">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="attribute" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="value">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="expand-rows" type="xs:boolean"/>
									<xs:attribute name="type" default="varchar">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="varchar" />
												<xs:enumeration value="filetime" />
												<xs:enumeration value="binarystring" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="length" default="255">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="1" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:group name="sql_or_ldap">
		<xs:choice>
			<xs:element name="query" type="xs:string"/>
			<xs:element ref="ldaptransfer"/>
		</xs:choice>
	</xs:group>
	<xs:element name="query">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="error" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sqltransfer">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="version">
					<xs:complexType>
						<xs:attribute name="number" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="1.0"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="execution">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="daily">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="time" type="xs:string" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="sources">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="source" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:string" minOccurs="0"/>
										<xs:element name="database" type="xs:string"/>
										<xs:group ref="connectiongroup"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="target">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="database" type="xs:string"/>
							<xs:element ref="jdbc"/>
							<xs:element name="sql" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="drop-table-syntax" type="xs:string" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="errors">
								<xs:complexType>
									<xs:all>
										<xs:element name="drop-table" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="head" type="xs:string"/>
													<xs:element name="tablename" type="xs:string"/>
													<xs:element name="tail" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="drop-table-message" type="xs:string" minOccurs="0"/>
									</xs:all>
								</xs:complexType>
							</xs:element>
							<xs:element name="prepare_database" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="query" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="typetranslation">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="type" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="sqltype" type="xs:string" use="required"/>
									<xs:attribute name="source" type="xs:string" use="required"/>
									<xs:attribute name="target" type="xs:string" use="required"/>
									<xs:attribute name="length" type="xs:boolean" use="required"/>
									<xs:attribute name="mindate" type="xs:date"/>
									<xs:attribute name="maxdate" type="xs:date"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="importtables">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="importtable" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="prequeries" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element ref="query" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="source_name" type="xs:string" minOccurs="0"/>
										<xs:group ref="sql_or_ldap"/>
										<xs:element name="tablename" type="xs:string"/>
										<xs:element name="append" type="xs:boolean"/>
										<xs:element name="postqueries" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element ref="query" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== K-Rhen/sqltransfer/src/main/resources/examples/sqltransfer_simpletest.xml
<?xml version="1.0" encoding="UTF-8"?>
<sqltransfer 
	xmlns="http://www.topdesk.com" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.topdesk.com sqltransfer.xsd"
>
	<version number="1.1"/>
 	<sources>
 		<source>
 			<name>H2</name>
 			<database>H2</database>
			<jdbc>
				<driver>org.h2.Driver</driver>
				<url>jdbc:h2:mem:source</url>
				<user>sa</user>
				<password></password>
			</jdbc>
 		</source>
	</sources>
	<target>
		<database>H2</database>
		<jdbc>
			<driver>org.h2.Driver</driver>
			<url>jdbc:h2:target</url>
			<user>sa</user>
			<password></password>
		</jdbc>
		<sql>
			<drop-table-syntax>drop table if exists %s</drop-table-syntax>
		</sql>
		<errors>
			<drop-table-message>Table %S not found [42102-100]</drop-table-message>
		</errors>
	</target>
	<typetranslation>
		<type sqltype="12"	source="VARCHAR"		target="varchar"		length="true"/>
		<type sqltype="4"	source="INTEGER"		target="integer"		length="false"/>
		<type sqltype="16"	source="BOOLEAN"		target="boolean"		length="false"/>
		<type sqltype="93"	source="TIMESTAMP"		target="timestamp"		length="false"/>
		<type sqltype="-1"	source="TEXT"			target="text"			length="false"/>
	</typetranslation>
	<importtables>
		<importtable>
			<source_name>H2</source_name>
			<query>select 'Test  successfull!' as test_string, '2008-08-01 13:32:45'::timestamp as test_timestamp</query>
			<tablename>target_table</tablename>
			<append>false</append>
			<postqueries>
				<query>
					insert into target_table (test_string, test_timestamp) values ('Again successfull!', current_date())
				</query>
			</postqueries>
		</importtable>
	</importtables>
</sqltransfer>
<!-- 
This is a list of a few of the most common data types, that Java knows for sql.

java.sql.Types
BIT 			=   -7;
TINYINT 		=   -6;
SMALLINT		=    5;
INTEGER 		=    4;
BIGINT 			=   -5;
FLOAT 			=    6;
REAL 			=    7;
DOUBLE 			=    8;
NUMERIC 		=    2;
DECIMAL			=    3;
CHAR			=    1;
VARCHAR 		=   12;
LONGVARCHAR 	=   -1;
DATE 			=   91;
TIME 			=   92;
TIMESTAMP 		=   93;
OTHER			= 1111;
BOOLEAN 		=   16;
-->
